#!/usr/bin/env bash

function print_usage {
    cat <<EOF
Script for deploying testing containers on cpk-front.mzk.cz.
After successful build and deploy, script echoes ULR on which container
is running.

USAGE: deploy_cpk [-b branch]

  -b                   Branch to use for build
  -c                   Config directory to use
  -l                   Enable shibboleth login [true|false], default enabled
  --help|-h            Print usage

EOF
}

branch="master"
config_dir=""
shib_login="true"
while true ; do
    case "$1" in
        -b)
            case "$2" in
                "") shift 2 ;;
                *) branch=$2;
                   echo "Processing argument: $1 = $2";
                   shift 2 ;;
            esac ;;
        -c)
            case "$2" in
                "") shift 2 ;;
                *) config_dir=$2;
                   echo "Processing argument: $1 = $2";
                   shift 2 ;;
            esac ;;
         -l)
             case "$2" in
                 "") shift 2 ;;
                 *) echo "Processing argument: $1 = $2";
                    shib_login=$2
                   shift 2 ;;
            esac ;;
        --help|-h)
            print_usage;
            exit 0;;
        *) break ;;
    esac
done

port=0
port_start=10000
port_end=10009
if [ "$shib_login" == "false" ]; then
    port_start=10010
    port_end=10019
fi
for i in $(seq "$port_start" "$port_end"); do
    docker_port=$((i+10000));
    if ! netstat -ln | grep ":$docker_port " | grep -q 'LISTEN'; then
        port=$i
        break
    fi
done

if [ $port = 0 ]; then
    echo "No free available port"
    exit 1
fi

if [ ! -z "$config_dir" ]; then
    export PARAM_VUFIND_CONFIG_DIR="$config_dir"
fi

service="devel-${port}"
http_port=$(($port+10000))
https_port=$(($port+10443))
container_name="vufind-devel-$branch"

./make-cpk -d -t devel -p $http_port -s $https_port -b $branch -service $service --name $container_name

echo "URL: https://cpk-front.mzk.cz:${port}/"
