version: '2.2'
services:
    devel:
        image: "localhost/${IMAGE_NAME:-cpk-devel}"
        extends:
            file: docker-compose.yaml
            service: cpk
        env_file:
           - devel.env
        build:
            context: "builds/cpk-source"
            args:
                PARAM_VUFIND_BRANCH: ""
                PARAM_VUFIND_COMMIT_HASH: ""
        volumes:
            - "./data/devel/:/data/"
            - "./certs:/var/www/cpk/certs:ro"
        network_mode: bridge
    devel-10000:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel-10000}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10000"
    devel-10001:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel-10001}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10001"
    devel-10002:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel-10002}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10002"
    devel-10003:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel-10003}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10003"
    devel-10004:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel-10004}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10004"
    devel-10005:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel-10005}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10005"
    devel-10006:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel-10006}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10006"
    devel-10007:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel-10007}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10007"
    devel-10008:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel-10008}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10008"
    devel-10009:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel-10009}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10009"
    devel-10010:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel-10010}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10010"
    devel-10011:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel-10011}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10011"
    devel-10012:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel-10012}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10012"
    devel-10013:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel-10013}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10013"
    devel-10014:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel-10014}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10014"
    devel-10015:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel-10015}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10015"
    devel-10016:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel-10016}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10016"
    devel-10017:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel-10017}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10017"
    devel-10018:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel-10018}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10018"
    devel-10019:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel-10019}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10019"
    devel-10020:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel-10020}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10020"
